### ISSUE TITLE
Allow strings to match files? The inverse?

### ISSUE THREAD

**Issue by milesj** [Turbo87/chai-files#8]
Loving the package so far as it somewhat solves my test case implementations instead of me writing it all myself. However, there's one feature I would like, which is comparing strings to files.

As of right, according to the docs, we can only test as such: `expect(file(path)).to.equal(string)`. What I would like to be able to do is the inverse: `expect(string).to.equal(file(path))`. Right now I'm solving this issue by faking the File object: https://github.com/milesj/reagent/blob/master/tests/Renderer-test.js#L37

I would like this as I have classes that generate output that _would_ be written to files or stdout, but would like to avoid having to actual write to files during the tests. Ideally just comparing the output to the expected file would be perfect.

**Comment by Turbo87** [comment]
@milesj should be possible. would you like to try implementing it?

**Comment by milesj** [comment]
I can look into it if you can direct me to the correct place.

**Comment by Turbo87** [comment]
your entry point would be around https://github.com/Turbo87/chai-files/blob/master/src/chai-files.js#L66-L74 which is essentially what gets called if you do `expect(...).to.equal(...);`

**Comment by milesj** [comment]
Cool thanks, looking into.

**Comment by Turbo87** [comment]
also there are plenty of unit tests for those features so it should be reasonably easy to step through them to get an understanding of what's going on

**Comment by Turbo87** [comment]
Fixed by #9
